---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Introduction {#intro}

Introdução Proposta

Para compreender a diversidade local é necessário considerar a influência da paisagem ao redor (REF), porém não se sabe muito bem como (REF). A dinâmica ecológica que influencia a abundância local pode ocorrer com taxas demográficas mais lentas do que as taxas de modificação da paisagem (PESQUISAR MELHOR REF). Detalhes da trajetória das paisagens e da biodiversidade associada são escassos (REF), uma abordagem é o de análise de dados estáticos de biodiversidade local e mapa de cobertura vegetal da paisagem ao redor. Nesses casos, procura-se amostrar regiões em que se espera que as taxas demográficas estejam respondendo à heterogeneidade da paisagem (e.g. Pardini et al. 2010??; Banks-Leite et al. 2014; Watling et al. 2020; Pütkker et al. 2020), assim há uma tendência de amostrar regiões com estimada baixa taxa líquida de desmatamento, e.g. grandes áreas de floresta contígua, ou em paisagens com alguma informação histórica disponível (REF). Trabalhos empíricos que usam esse tipo de abordagem dialogam com trabalhos teóricos que consideram a situação de equilíbrio das populações na heterogeneidade da paisagem (REF Hanski 2011, 2015, mas veja REF). Em biomas com grande dinamismo ainda hoje, como a Floresta Atlântica, mesmo paisagens com perda líquida nula a configuração espacial da cobertura vegetal pode mudar (Rosa et al. 2021), e a configuração espacial contemporânea pode aproximar mal a influência da geometria da cobertura vegetal na movimentação dos indivíduos ao longo do tempo (Martensen et al. 2017). Nesses casos, uma alternativa é pressupor ausência da influência da distância entre fragmentos, então a biodiversidade local se torna uma função apenas da quantidade de cobertura vegetal remanescente na paisagem (Fahrig 2013). Por outro lado, quando há muita incerteza sobre o histórico da área ou se o desmatamento é muito severo e recente, uma alternativa é pressupor que a paisagem contemporânea não tem influência na biodiversidade local (Fahrig et al. 2022), o equilíbrio pode ter sido atingido anteriormente em uma paisagem sem desmatamento (May et al. 2019), uma vez que o atraso na resposta ecológica (e.g. débito de extinção e crédito de imigração) pode levar centenas de anos para alguns táxons em certos contextos (Lira et al. 2019, Figueiredo et al. 2019, REF).

Os trabalhos teóricos que pressupõem equilíbrio sugerem que uma variável chave é a proporção de cobertura vegetal na paisagem, pois ao passo que se perde cobertura vegetal e a paisagem passa o limiar de percolação os fragmentos remanescentes podem se tornar menores e mais isolados, populações perdidas localmente podem não ser repostas enquanto outras podem aumentar em abundância relativa; com a redução para proporções abaixo de níveis intermediários há também a redução do número de fragmentos possíveis, levando à perda de espécies na paisagem que estavam restritas aos fragmentos perdidos. Além disso, a redução no habitat disponível aumenta o risco de extinção local e mesmo populações especialistas podem se extinguir em condições favoráveis. Por isso, uma expectativa é que exista redução não linear da diversidade local com a perda de cobertura vegetal na paisagem ao redor. A posição do limiar deve depender dos requerimentos de habitat das espécies no pool de espécies que chegam e da conectividade da paisagem (REF Hanski REF). Em proporções intermediárias há maior variação na possível configuração espacial do habitat e maior chance de corredores ecológicos ou stepping stones contribuírem com o aumento da movimentação de indivíduos de fragmentos com capacidade de manter populações viáveis (Villard & Metzger 2014, Pardini et al. 2010). Se o equilíbrio foi atingido na paisagem em uma configuração próxima da contemporânea, então pode não ser suficiente pressupor apenas a quantidade de habitat, se a particular configuração espacial restringir a movimentação dos indivíduos sob limitação de dispersão. Por outro lado, pressupor que o equilíbrio foi atingido em uma paisagem sem perda de habitat, com todo o possível atraso na resposta ecológica (débito de extinção e crédito de imigração), sugere que a perda de cobertura vegetal influenciou apenas a diversidade remanescente na paisagem ao redor e não a diversidade local.

Aqui investigamos o efeito de pressupor equilíbrio na paisagem contemporânea em comparação ao equilíbrio em uma paisagem idealizada íntegra e o de pressupor a configuração espacial da cobertura vegetal em comparação com apenas a quantidade de cobertura vegetal na construção de modelos para descrever a diversidade local de árvores e a sua relação com a paisagem ao redor. Procuramos predizer a distribuição de abundância de espécies (SAD) observada em inventários florestais que amostraram parcelas de Floresta Atlântica, uma ecorregião que vem perdendo e ganhando cobertura vegetal com diferentes taxas há mais de 500 anos, resultando em uma cobertura remanescente total inferior à 20% e paisagens ao longo de um gradiente de cobertura vegetal (PESQUISAR MAIS REF). Os mapas de cobertura vegetal mais detalhados iniciam em 1985 (Rosa et al. 2021), anterior a essa data a informação disponível é limitada e variável entre regiões (PESQUISAR MAIS REF). Usamos a teoria neutra da biodiversidade para construir 4 modelos baseados em indivíduos que compartilham pressupostos mas diferem em como conceitualizam a dispersão dos indivíduos entre a parcela e a paisagem. Nos modelos neutros, o equilíbrio ocorre quando o número de espécies perdidas pela competição neutra por espaço (deriva ecológica) é balanceado pela constante colonização de novas espécies na paisagem. Interpretamos os modelos neutros que pressupõem a quantidade de cobertura vegetal (espacialmente implícito) como uma simplificação dos modelos que consideram a configuração espacial da cobertura vegetal remanescente (espacialmente explícito) e simulamos cenários de limitação à dispersão variando a proporção de propágulos que permanecem na vizinhança imediata da progenitora até a ausência de limitação de dispersão per capita.

```{r}
install.packages("trackdown")
remotes::install_github("claudiozandonella/trackdown", build_vignettes = TRUE)
library(trackdown)
library(googledrive)
trackdown::update_file(file = "01-intro.Rmd",
                       gpath = "mestrado/manuscrito/",# para indicar uma pasta não use ~/ ou ./ apenas o nome da pasta
                       hide_code = TRUE) 
drive_ls("~/mestrado/manuscrito")
```

